# example values

indexing-settings:
  sites:
    - url: https://www.lenta.ru
      name: Лента.ру
    - url: https://www.skillbox.ru
      name: Skillbox
    - url: https://www.playback.ru
      name: PlayBack.Ru

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db
    username: root
    password: Benjamin1*
  liquibase:
    change-log: classpath:/db/changelog/changelog.xml
